spring:
  datasource:    url: jdbc:postgresql://localhost:5432/ArtistfyDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true 